local moonbug = require "moonbug.moonbug"

moonbug.compat.libs.socket = require "builtins.scripts.socket"
moonbug.compat.log_print = pprint

go.property("enable_debugger", true)
go.property("port", 8888)
go.property("wait", false)
go.property("stop_on_entry", false)
go.property("stop_on_attach", false)

---@class Debugger
---@field enable_debugger boolean Enable the debugger
---@field port            integer The debugger port
---@field wait            boolean Block until debugger attaches
---@field stop_on_entry   boolean Stop the process when debugger configuration is done
---@field stop_on_attach  boolean Stop the process when debugger attaches

---@param self Debugger
function init(self)
    if not self.enable_debugger then
        return
    end

    print(string.format("Debugger has been enabled on port %d", self.port))

    moonbug.listen(nil, tonumber(os.getenv "MOONBUG_PORT") or self.port, {
        wait = self.wait,
        stop_on_entry = self.stop_on_entry,
        stop_on_attach = self.stop_on_attach,
    })
end
